### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by dqf318** [Gamebunn/Cream64_PC#4]
When I try to compile, I get this:
"make[1]: *** [Makefile:37: n64graphics] Error 1
Traceback (most recent call last):
  File "/home/dqf31/Cream64_PC/extract_assets.py", line 301, in <module>
    main() if __name__ == "__main__" else None
    ^^^^^^
  File "/home/dqf31/Cream64_PC/extract_assets.py", line 170, in main
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/sm64tools/', 'n64graphics', 'mio0']' returned non-zero exit status 2.
Makefile:422: *** Failed to extract assets from US ROM.  Stop."

Any idea what to do?

**Comment by dqf318** [comment]
Never mind.  All I had to do was add more to MSYS2.
